spring:
  datasource:
    url: jdbc:mysql://www.cxx.space:3306/mooc_meetingfilm?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: josh5209
    password: Fei@8807
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
debug: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-underline: true
  mapper-locations: classpath*:mapper/*Mapper.xml
logging:
  level:
    com.example.meeting.mapper: trace
